### ISSUE TITLE
> Added extra on Posters Text.

### ISSUE THREAD

**Issue by SensehacK** [SensehacK/SensehacK.github.io#66]
**Describe the bug** 
Extra  > on Posters Text description.

**To Reproduce**
1. Go to 'Social'
2. Click on 'Third Poster'
3. See error

**Expected behavior**
Simple Text without extra tag.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome

**Comment by r4vaa** [comment]
I'll work on this 👍 @SensehacK
