### ISSUE TITLE
Song artwork too small.

### ISSUE THREAD

**Issue by debashismoharana** [SensehacK/SensehacK.github.io#70]
**Describe the bug**
Small artwork appears in the listening history.

**To Reproduce**
1. Go to '.Website.'
2. Click on 'Social'
3. Scroll down to 'Music'

**Expected behavior**
Music artwork should be bigger size.

**Screenshots**

![screen shot 2019-01-16 at 1 43 18 pm](https://user-images.githubusercontent.com/15375367/51235192-e2a79b00-1994-11e9-9918-9b4cf303c175.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS High Sierra]
 - Browser [chrome cannary, chrome]
 - Version [73, 71]

**Comment by SensehacK** [comment]
Hi @debashismoharana ,

Thanks for bug report.
